services:
  - type: web
    name: bank-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mybackend.wsgi
    preDeployCommand:
      python manage.py makemigrations
      python manage.py migrate
      python manage.py create_admin
      python manage.py collectstatic --noinput
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False" 
