services:
  - type: web
    name: bank-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mybackend.wsgi
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False" 