# Generated by Django 5.2.1 on 2025-06-14 13:41

from django.db import migrations, models
import random
import string

def generate_account_number(existing_numbers):
    while True:
        account_number = ''.join(random.choices(string.digits, k=10))
        if account_number not in existing_numbers:
            existing_numbers.add(account_number)
            return account_number

def assign_account_numbers(apps, schema_editor):
    CustomUser = apps.get_model('app', 'CustomUser')
    existing_numbers = set(
        CustomUser.objects.exclude(account_number='').values_list('account_number', flat=True)
    )
    for user in CustomUser.objects.all():
        if not user.account_number:
            user.account_number = generate_account_number(existing_numbers)
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(null=True, blank=True, max_length=10, unique=True),
        ),
        migrations.RunPython(assign_account_numbers),
    ]
