# Generated by Django 5.2.1 on 2025-06-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transaction_processed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='transaction_type',
        ),
    ]
