# Generated by Django 5.2.1 on 2025-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_type_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
