# Generated by Django 5.2.1 on 2025-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_transaction_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer'), ('loan', 'Loan')], max_length=10),
        ),
    ]
