# Generated by Django 5.2.1 on 2025-06-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_loan_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
